import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <div className="w-full m-0 p-0 bg-black">
            <Head>
                <title>Country App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen p-16 flex-1 flex flex-col justify-center content-center">
                <h1 className="text-2xl text-indigo-700 text-center">Hello world!</h1>
                <p className="indent-4 hover:indent-16 text-white">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                    nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </main>
            {/* {styles.footer} */}
            <footer className="flex flex-1 p-8 border-t-2 border-indigo-900 justify-center content-center text-white">
                <p>Footer</p>
            </footer>
        </div>
    );
};

export default Home;
